- includes:
    .:
      config_file: tulip.yaml # my current workplace

- defaults:
    link:
      create: true
      relink: true

# I might want to reenable this. I want to read up on it, it might be dangerous.
# - clean: 
#   ~/:
#     force: true
#   ~/.config:
#     recursive: true
#     force: true

- create:
  - ~/Projects # These are mostly closed source projects that I'm working on.
  - ~/GitHub # These are open source projects that I'm interested in or I'm working at.
  - ~/Pictures/Screenshots # I like to have a folder where my screenshots gets saved, although I should probably save them straight to Dropbox instead.
  - ~/Projects # These are mostly closed source projects that I'm working on.
  - ~/.config
  - ~/.local
  - ~/.local/snippets
  - ~/.local/snippets/vscode
  - ~/.local/snippets/luasnippets
  - ~/.fonts
  - ~/.neomutt

- link:
    ~/.config/:
      glob: true
      path: files/config/*
      relink: true
      create: true
    ~/.local/bin:
      glob: true
      path: files/local/bin/*
      relink: true
      create: true
    ~/.fonts/:
      glob: true
      path: files/.fonts/*
      relink: true
      create: true
    ~/.asoundrc: files/.asoundrc # setting type pulse
    ~/.markdownlintrc: files/.markdownlintrc # for markdownlint-cli
    ~/.zshrc: files/.zshrc
    ~/.zshenv: files/.zshenv
    ~/.inputrc: files/.inputrc
    ~/.gitconfig: files/.gitconfig
    ~/.neomutt/profile.personal: files/neomutt/profile.personal
    ~/.mailcap: files/mailcap

- shell:
  # This line must be included in all configurations as I'm depending on submodules for "includes" and "sudo"
  - [git submodule update --init --recursive, Installing and updating submodules]
  # I found out about hub, I'm planning to use `hub clone` to quickly get a repo. It should be fetched through SSH.
  - [git config --global hub.protocol ssh]
