return {}
-- return {
--   "echasnovski/mini.clue",
--   version = false,
--   event = "VeryLazy",
--   opts = {
--     triggers = {
--       { mode = "n", keys = "<leader>dd" },
--     },
--   },
-- }
