return {
	s(
		"t-github-pull-request-template",
		t({
			"## Summary",
			"",
			"## Jira Task",
			"- [x] No ticket needed (check only if level of impact is No-op)",
			"",
			"## Level of Impact",
			"Please select exactly one option. To change the level of impact, first unselect the current level of impact and then select the new level of impact.",
			"",
			"- [ ] 1 - High",
			"- [ ] 2 - Medium",
			"- [ ] 3 - Low",
			"- [x] 4 - No-op",
			"",
			"## Impact Analysis",
			"N/A",
			"## Release Notes",
			"N/A",
			"## Release Change Category",
			"Please select exactly one option. To change the release change category, first unselect the current category and then select the new one.",
			"",
			"- [x] 1 - Internal Only (Non Customer Facing)",
			"- [ ] 2 - Bug Fix (Customer Facing)",
			"- [ ] 3 - New Feature",
			"- [ ] 4 - Feature Enhancement",
			"- [ ] 5 - Feature Deprecated",
			"- [ ] 6 - Release Change Category Not Needed",
			"",
			"## Feature Flags",
			"N/A",
			"## Test Plan",
			"N/A",
			"## Checklist",
			"Check each when they are done or confirmed to not apply. If something here isn't checked, this isn't ready to be merged. Seriously. You are making your colleagues lives a lot easier by doing this consistently. Be a good Tulipian.",
			"",
			"- [x] [Test Plan Fully Executed](https://tulipmfg.atlassian.net/wiki/spaces/PLAT/pages/2352742443/Test+Plan)",
			"- [x] [Cypress Tests](https://tulipmfg.atlassian.net/wiki/spaces/PLAT/pages/2352742443/Test+Plan)",
			"- [x] [Does not require security review or security review complete](https://tulipmfg.atlassian.net/wiki/spaces/PLAT/pages/8093713/Security+Review+process)",
			"",
			"For more information on the requirements for every pull request, see [Development Definition of Done](https://tulipmfg.atlassian.net/wiki/spaces/PLAT/pages/2352382014/Development+Definition+of+Done).",
			"",
		})
	),
}
