# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "($status\n)$directory $shlvl $python\n$character"
add_newline = true
scan_timeout=100 # 30 is the default
palette="moonfly"


[status]
disabled=false
format='[\(exit_code: $int\)]($style)'
map_symbol=true
style='greyk'

[golang]
disabled=true

[python]
disabled=false

[git_metrics]
disabled=false
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[shlvl]
disabled=false

[aws]
disabled=true
format = 'on [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
style = 'bold greym'
symbol = '🅰 '

[directory]
disabled=false
truncation_length = 0
truncate_to_repo=false
style='bold greyf'

[character]
success_symbol = '[➜](bold emerald)'
error_symbol = '[✗](bold crimson)'
vimcmd_symbol = '[V](bold sky)'

[palettes.moonfly]
black = '#080808'
white = '#c6c6c6'
blue = '#80a0ff'
sky = '#74b2ff'
green = '#8cc85f'
emerald = '#36c692'
yellow = '#e3c78a'
khaki = '#c2c292'
cyan = '#79dac8'
magenta = '#ff5189'
crimson = '#ff5189'
red = '#ff5454'
greya = '#323437'
greyb = '#373c4d'
greyc = '#e4e4e4'
greyd = '#b2b2b2'
greye = '#9e9e9e'
greyf = '#949494'
greyg = '#808080'
greyh = '#626262'
greyi = '#4e4e4e'
greyj = '#444444'
greyk = '#3a3a3a'
greyl = '#303030'
greym = '#262626'
greyn = '#1c1c1c'
greyo = '#121212'
orange = '#de935f'
purple = '#ae81ff'
