# 0: heuristic overcommit (this is the default)
# 1: always overcommit, never check
# 2: always check, never overcommit
vm.overcommit_memory = 1

# vm.overcommit_ratio = 60
# vm.swappiness = 200
# vm.swappiness = 70

fs.inotify.max_user_watches=1048576

# mongo: We suggest setting swappiness to 0 or 1, as swapping can cause performance problems.
vm.swappiness = 0

vm.nr_hugepages = 1024

# mongo, elastic: increase virtual memory
vm.max_map_count=262144

net.ipv4.tcp_fastopen = 3
#vm.watermark_scale_factor=2000

# Example illustration of current printk setting (4 4 1 7).
#                      CUR  DEF  MIN  DEFCON
# 0 - emergency        x               x
# 1 - alert            x          x    x
# 2 - critical         x               x
# 3 - error            x               x
# 4 - warning                x         x
# 5 - notice                           x
# 6 - informational                    x
# 7 - debug
kernel.printk= 3 3 3 3
