[font]
size = 19
hinting = "full"
edging = "antialias"

# Regular

[[font.normal]]
family = "PragmataPro Mono"
style = "Regular"

[[font.normal]]
family = "Noto Sans Mono"
style = "Regular" # only Regular and Bold is supported

[[font.normal]]
family = "Noto Sans CJK SC"
style = "Regular" # only Regular and Bold is supported

[[font.normal]]
family = "Noto Sans CJK JP"
style = "Regular" # only Regular and Bold is supported

[[font.normal]]
family = "Noto Sans CJK KR"
style = "Regular" # only Regular and Bold is supported

# Bold
[[font.bold]]
family = "PragmataPro Mono"
style = "Bold"

[[font.bold]]
family = "Noto Sans Mono"
style = "Bold" # only Regular and Bold is supported

[[font.bold]]
family = "Noto Sans CJK SC"
style = "Bold" # only Regular and Bold is supported

[[font.bold]]
family = "Noto Sans CJK JP"
style = "Bold" # only Regular and Bold is supported

[[font.bold]]
family = "Noto Sans CJK KR"
style = "Bold" # only Regular and Bold is supported
