maple: &maple 'Maple Mono NF:style=Semibold:size=16'
std_underline: &std_underline {underline: { size: 2, color: 79dac8ff}}

bar:
  height: 32
  location: bottom
  background: 000000ff
  font: *maple
  border:
    top-width: 1
    color: 111111ff
  left:
    - i3:
        anchors:
          - string: &i3_common {margin: 10, on-click: "swaymsg --quiet workspace {name}"}
          - string: &default {<<: *i3_common, text: "{name}"}
          - focused: &focused
              deco: {stack: [background: {color: 79dac84c}, <<: *std_underline]}
          - invisible: &invisible {foreground: ffffff55}
          - urgent: &urgent
              foreground: 000000ff
              deco: {stack: [background: {color: bc2b3fff}, <<: *std_underline]}
          - map: &i3_mode
              default:
                - string:
                    margin: 5
                    text: "{mode}"
                    deco: {background: {color: cc421dff}}
                - empty: {right-margin: 7}
              conditions:
                mode == default: {empty: {}}
        content:
          "${W1}": &conditions-map
            map:
              conditions:
                state == focused:   {string: {<<: [*default, *focused]}}
                state == unfocused: {string: {<<: *default}}
                state == invisible: {string: {<<: [*default, *invisible]}}
                state == urgent:    {string: {<<: [*default, *urgent]}}
          "${W2}": *conditions-map
          "${W3}": *conditions-map
          "${W4}": *conditions-map
          "${W5}": *conditions-map

        sort: ascending

    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "<", left-margin: 16 }
                - string: {text: "{app-id}", foreground: 79dac8ff}
                - string: {text: ": {title}>"}

  right:
    - mem:
        content:
          - string: {text: "MEM: {percent_used}%", margin: 8}
    - cpu:
        content:
          map:
            conditions:
              id < 0:
                - string: {text: "CPU: {cpu}%", margin: 8}
    - sway-xkb:
        identifiers: [13364:832:Keychron_Keychron_V4_Keyboard]
        content:
          - string: {text: "{layout}", margin: 8}
    - clock:
        content:
          - string: {text: "{date}", margin: 8}
          - string: {text: "{time}", right-margin: 12}

