-- The new file explorer to experiment with after vim-vinegar
return {}
-- return {
--   "nvim-tree/nvim-tree.lua",
--   lazy=false, -- weird buffer rename issues on startup without this
--   dependencies = {
--     "nvim-tree/nvim-web-devicons", -- optional, for file icons
--   },
--   keys = {
--     {
--       "-",
--       function()
--         -- Search for file on the dashboard instead
--         if vim.o.filetype == "alpha" then
--           vim.api.nvim_input( "\\sf" )
--           return
--         end
--
--         -- weird situation, I have opened up nvim-tree on the side but then I can't enter
--         -- open it without having weird sizing issues.
--         -- if vim.o.filetype == "alpha" then
--         -- 	require("nvim-tree").toggle(true, false, vim.fn.getcwd(), false)
--         -- 	print('open_mode: ', vim.o.open_mode)
--         -- else
--         -- ...
--         local view = require"nvim-tree.view"
--         local api = require"nvim-tree.api"
--         if view.is_visible() then
--           api.tree.close()
--         else
--           require"nvim-tree".open_replacing_current_buffer()
--         end
--
--       end,
--       desc = "Open File Explorer",
--       noremap = true,
--     }
--   },
--   opts = function()
--     require("nvim-tree").setup({
--       disable_netrw = true,
--       open_on_setup = false,
--       open_on_setup_file = false,
--       ignore_buffer_on_setup = false,
--       hijack_directories = {
--         enable = true,
--         auto_open = true
--       },
--       -- project.nvim integration
--       sync_root_with_cwd = true,
--       respect_buf_cwd = true,
--       update_focused_file = {
--         enable = true,
--         update_root = true
--       },
--       view = {
--         -- Resize the window on each draw based on the longest line. adaptive_size = true,
--         -- Preserves window proportions when opening a file.
--         preserve_window_proportions = false,
--         mappings = {
--           list = {
--             { key = "<CR>", action = "edit_in_place"}
--           }
--         }
--       },
--       actions = {
--         open_file = {
--           quit_on_open = true
--         }
--       },
--       remove_keymaps = false,
--       renderer = {
--         -- Appends a trailing slash to folder names.
--         add_trailing = true,
--         -- Enable file highlight for git attributes using `NvimTreeGit*` highlight groups.
--         highlight_git = true,
--         -- Highlight icons and/or names for opened files.
--         -- Value can be `"none"`, `"icon"`, `"name"` or `"all"`.
--         highlight_opened_files = "all",
--
--         indent_width = 2,
--         indent_markers = {
--           -- Display indent markers when folders are open
--           enable = true,
--           -- Display folder arrows in the same column as indent marker
--           inline_arrows = true,
--           icons = {
--             corner = "└",
--             edge = "│",
--             item = "│",
--             bottom = "─",
--             none = " ",
--           },
--         },
--         icons = {
--           glyphs = {
--             folder = {
--               arrow_closed = ">",
--             },
--           },
--         },
--       },
--     })
--   end,
-- }
